# Generated by Django 5.2.16 on 2026-07-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target_model', models.CharField(help_text="e.g., 'Product' or 'Order'", max_length=100)),
            ],
            options={
                'db_table': 'azt_workflow_states',
                'unique_together': {('name', 'target_model')},
            },
        ),
    ]
