# Generated by Django 5.2.16 on 2026-08-03 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowstate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='label',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='workflowstate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workflowstate',
            name='target_model',
        ),
    ]
