# Generated by Django 5.2.16 on 2026-07-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='primary_color',
            field=models.CharField(default='#d01345', help_text='Main action color (Hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='secondary_color',
            field=models.CharField(default='#2d2d2d', help_text='Main text/dark color (Hex)', max_length=7),
        ),
    ]
