# Generated by Django 5.2.16 on 2026-07-31 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_utils', '0001_initial'),
        ('utils', '0003_role_status_brand_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_per_item',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Internal cost for ERP profit calculations — never expose this in a public-facing serializer', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Cover image shown on listing cards')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='utils.product')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_status', to='base_utils.workflowstate')),
            ],
            options={
                'db_table': 'azt_product_images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute_name', models.CharField(help_text="e.g. 'Size', 'Color'", max_length=50)),
                ('attribute_value', models.CharField(help_text="e.g. 'M', 'Red'", max_length=50)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='utils.product')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_status', to='base_utils.workflowstate')),
            ],
            options={
                'db_table': 'azt_product_variants',
                'ordering': ['attribute_name', 'attribute_value'],
                'unique_together': {('product', 'attribute_name', 'attribute_value')},
            },
        ),
    ]
